### ISSUE TITLE
urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!

### ISSUE THREAD

**Issue by Drjacky** [abirabedinkhan/Ducky-Script-Compiler#1]
The txt content is:
```
STRING 0000001
ENTER
DELAY 5000
....

```
I got this:
```bash
/opt/homebrew/lib/python3.11/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
^CTraceback (most recent call last):
  File "Ducky-Script-Compiler/main.py", line 106, in <module>
    lex(line, prev)
  File "Ducky-Script-Compiler/main.py", line 46, in lex
    time.sleep(float(line[6:]) / 1000)
```

**Comment by abirabedinkhan** [comment]
can u run this
```
pip3 install --upgrade requests
```
Try running the script again.
